### ISSUE TITLE
ValueError: options should not be an empty list

### ISSUE THREAD

**Issue by shvchk** [rodfersou/osx-ntfs-rw#1]
```
% sudo ntfs-rw
Traceback (most recent call last):
  File "/Users/x/.local/bin/ntfs-rw", line 8, in <module>
    sys.exit(main())
  File "/Users/x/.local/pipx/venvs/osx-ntfs-rw/lib/python3.10/site-packages/ntfs_rw/main.py", line 53, in main
    disk = select_disk()
  File "/Users/x/.local/pipx/venvs/osx-ntfs-rw/lib/python3.10/site-packages/ntfs_rw/main.py", line 47, in select_disk
    selected, _ = pick(disks)
  File "/Users/x/.local/pipx/venvs/osx-ntfs-rw/lib/python3.10/site-packages/pick/__init__.py", line 211, in pick
    picker: Picker = Picker(
  File "<string>", line 12, in __init__
  File "/Users/x/.local/pipx/venvs/osx-ntfs-rw/lib/python3.10/site-packages/pick/__init__.py", line 50, in __post_init__
    raise ValueError("options should not be an empty list")
ValueError: options should not be an empty list
```

**Comment by shvchk** [comment]
Also, disk type can contain spaces:
```
1:       Microsoft Basic Data ⁨easystore⁩               2.0 TB     disk6s1
```

This means result of a split in [src/ntfs_rw/main.py#L18](https://github.com/rodfersou/osx-ntfs-rw/blob/main/src/ntfs_rw/main.py#L18) might not always be as expected.
